### PR TITLE
All images converted from JPG to SVG. "Connectors.adoc" updated. Local version generated - all is OK.

### PR DESCRIPTION
**Pull request by DmitriGit**
Hello Team, if you are not so much against it, I'll create sometimes Pull Requests such that with a subset of converted images so you can evaluate colors, styles, ecc. and I can take, in time, into account your observations for rest of images I'm converting.

Thank you,
Dmitri.

### CODE REVIEW

**Comment by DmitriGit** [comment]
Hello,
done!!!

It was difficult task but I did it! :)

Before commit and push I'he:
1) synchronized with your changes,
2) generated documentation on my PC
3) controlled generated documentation.

Now the generated specification is of 4 megabyte istead of 60 megabyte. :)

All seems OK. Let me know if you have problems.

Thank you again,
Dmitri.

**Comment by DmitriGit** [comment]
Corrections and observations during image conversion:

(*) "conn-52" - at the left the main rectangle should be "Application Server" istead of "Resource Adapter" I think, so I wrote "Application Server".
(*) There are two "Web Browser" in the block at the left. May be one should be "Internet" as in 180.jpg?
(*) "conn-62" - I'he added points after "Connection" and "ManagedConnection" because original picture "conn-65" had points after "ManagedConnection".
(*) "conn-65" - I'he added points after "Connection" and "ManagedConnection" because original picture "conn-65" had points after "ManagedConnection".
(*) "conn-32" - Where is the step "8)" ? 
(*) "conn-43" - I'he corrected "implelemntation" to "implementation".
(*) "conn-55" - created as it was original "JPG" version - let me know if and how you want to finish it.
(*) "conn-56" - created as it was original "JPG" version - let me know if and how you want to finish it. Only one correction: in "ManagedConnectioncleanup" a point inserted to have "ManagedConnection.cleanup"
(*) "conn-141" - I'he corrected "Reposritory" to "Repository".
(*) "conn-127" - There are two phrases "Resource Adapter" on the original picture. Let me know if you want only one (out of the rectangle) so I delete the second (inside the rectangle).
(*) "conn-127" - In my version "workAccepted()" is without space between "work" and "Accepted".
(*) "conn-127" - I'he corrected "Secuirty" to "Security" in "setupSecurityContext()".
(*) "conn-78" - In my version "workAccepted()" is without space between "work" and "Accepted".
(*) "conn-105" - In my version "setup for message delivery" start with uppercase "S" because all other steps starts with uppercase letter.
(*) "conn-105" - In my version "9. Supply the ActivationSpec JavaBean and administered objects (if any), and specify the chosen resource adapter." finishes with point because all other steps finish with points.
(*) "conn-108" - Attention that "10. afterDelivery()" and "10. complete transaction" have both number "10". If you want I update numbers.
(*) "conn-130" - Attention: there is "5.3.2" without "5.3.1".
(*) "conn-131" - Attention: there is "5.3.2" and "5.3.3" without "5.3.1".
(*) "conn-184" - In my version "3. scheduleWork() [startWork() or doWork() may be used as well]" has not spaces between:
	1) "schedule" and "Work"
	2) "do" and "Work"
(*) "conn-121":  
	1) In the original version: "the transaction i in-doubt", in my version: "the transaction is in-doubt"	
	2) In the original version: "Whne the application server recorvers", in my version: "When the application server recovers"
(*) "conn-122":  
	1) In the original version: "1. create an Xid", in my version: "1. create a Xid"
	2) In the original version: "4. construct an Xid", in my version: "4. construct a Xid"	
(*) "conn-157": In the original version: "createConnectionFactort(ConnectionManager)", in my version: "createConnectionFactory(ConnectionManager)"
(*) "conn-120": 
	1) In the original version: "The above seqience", in my version: "The above sequence"
	2) In the original version: "rpllback", in my version: "rollback"
(*) "conn-140" - Attention: "RecordFactory" to "Record" line is without arrow in the original version. Let me know if I should insert it and resend you corrected version

Thank you,
Dmitri.

**Comment by smillidge** [comment]
Hi Dmitry. I've been through and generated and checked locally. I will merge this and if there are any further issues we can look at creating corrective PRs.

**Review by smillidge — APPROVED** [review]

**Comment by DmitriGit** [comment]
Yes, if you will find some issues I'll correct them immediately!

Thank you, Steve!
Dmitri.

**Pull request merged**
