### PR TITLE
jakartaize JCA specification document, section 24 - 36

### PR DESCRIPTION
**Pull request by bbulk**
Hi,
I updated section 24 to 36 in this pull request according to this guide: https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc

edit: for the legal agreement, I'm still waiting for a confirmation mail in the registration process

### CODE REVIEW

**Comment by smillidge** [comment]
Thanks just waiting for the confirmation on the ECA

**Comment by bbulk** [comment]
I created an eclipse account and signed the ECA. Is there anything else to do? Or do I just have to wait now?

**Comment by smillidge** [comment]
When you login at Eclipse.org do you have a green tick next to Eclipse Contributor Agreement under Status in the top left?

**Comment by bbulk** [comment]
Yes.
image

**Comment by smillidge** [comment]
OK I've triggered a revalidation of the PR

**Comment by smillidge** [comment]
OK now the problem is you didn't do `git commit -a -s` on your commits.

**Comment by bbulk** [comment]
ok, thanks. I'll fix that.

**Pull request merged**
